-- phpMyAdmin SQL Dump
-- version 5.0.2
-- https://www.phpmyadmin.net/
--
-- Host: localhost
-- Generation Time: Dec 14, 2020 at 08:57 PM
-- Server version: 10.4.14-MariaDB
-- PHP Version: 7.3.23

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `she8_catalog_dst`
--

-- --------------------------------------------------------

--
-- Table structure for table `craft`
--

CREATE TABLE `craft` (
  `item_name` varchar(100) NOT NULL,
  `item_description` text NOT NULL,
  `img_filename` varchar(100) DEFAULT NULL,
  `category` varchar(100) NOT NULL,
  `science_requirement` varchar(100) NOT NULL,
  `require_item1` varchar(100) NOT NULL,
  `require_item1_num` int(10) NOT NULL,
  `require_item2` varchar(100) NOT NULL,
  `require_item2_num` int(10) NOT NULL,
  `require_item3` varchar(100) NOT NULL,
  `require_item3_num` int(10) DEFAULT NULL,
  `damage` varchar(100) NOT NULL,
  `durability` varchar(100) NOT NULL,
  `item_id` int(50) NOT NULL,
  `how_to_obtain` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `craft`
--

INSERT INTO `craft` (`item_name`, `item_description`, `img_filename`, `category`, `science_requirement`, `require_item1`, `require_item1_num`, `require_item2`, `require_item2_num`, `require_item3`, `require_item3_num`, `damage`, `durability`, `item_id`, `how_to_obtain`) VALUES
('Axe', 'The Axe is a Tool that can be used to chop down Trees. It can be crafted at the beginning of the game with 1 Twig and 1 Flint. An Axe can also be used as a weapon, dealing 27.2 Health damage on each hit. With either usage, an Axe has enough durability for 100 swings. When used to chop down Trees, Axe requires 5 chops for small, 10 for medium, and 15 for large Trees. Dead or burnt Trees require only one swing. Currently, the amount of chopping requires is independent of the type of the Tree.', 'Axe.png', 'Tools', 'No Science requirement', 'Twigs', 1, 'Flint', 1, '', 0, '27.2', '100 uses', 5, 'Crafting on the left side tool bar. Always available.'),
('Shovel', 'The Shovel is a tool that can be used to dig up Plants and other objects in the Don\\\'t Starve world. It requires 2 Twigs and 2 Flint to craft and a Science Machine to prototype. It has 25 uses, and each use will take 4% of its durability. Shovel can also be used as a weapon, dealing 17 damage per strike. Each hit as a weapon will consume one use.', 'Shovel.png', 'Tools', 'Science Machine', 'Twigs', 2, 'Flint', 2, '', 0, '17', '25 uses', 6, 'It requires 2 Twigs and 2 Flint to craft and a Science Machine to prototype.'),
('Pickaxe', 'The Pickaxe is a Tool that can be used to mine Mineable objects. It can be crafted at the beginning of the game with 2 Twigs and 2 Flint. It takes 6 strikes to completely mine down a Boulder. It has 33 uses, and each strike will reduce its durability by 3%. Pickaxes can also be used as a weapon, dealing 27.2 damage per strike. Each strike as a weapon also counts as one use.', 'Pickaxe.png', 'Tools', 'No Science requirement', 'Twigs', 2, 'Flint', 2, '', 0, '27.2', '33 uses', 9, 'It can be crafted at the beginning of the game with 2 Twigs and 2 Flint.'),
('Hammer', 'The Hammer is a Tool that can be used to demolish Structures. The Hammer requires 3 Rocks, 3 Twigs, and 2 Rope to craft and a Science Machine to prototype. Hammers can break down any player-made Structures and most naturally occurring Structures such as Pig Houses, yielding at least 50% of the materials used to create the Structure in most cases. If the player strikes a container such as a Chest or Crock Pot, all items within will fly out but remain undamaged. It also can be used on an Ancient Pseudoscience Station and Ornate Chest, both of which are found in the Ruins, to make random effects and objects appear.', 'Hammer.png', 'Tools', 'No Science requirement', 'Twigs', 3, 'Flint', 3, 'Cut_Grass', 6, '17', '75 uses', 10, 'The Hammer requires 3 Rocks, 3 Twigs, and 2 Rope to craft and a Science Machine to prototype.'),
('Pitchfork', 'Once the Pitchfork is equipped, a square outline will appear on the ground showing the patch that the cursor is hovering over, along with a prompt. Right-clicking will dig up the outlined terrain, leaving a barren patch in its place. Turf items can only be placed on this sort of barren terrain. \\r\\n\\r\\nThe Pitchfork has 200 uses, which means that each time it digs up a turf, it will lose 0.5% durability. It can also be used as a weapon which deals 17 damage but suffers higher durability loss per hit (4%). \\r\\n\\r\\nA Turf\\\'s instant availability and decent fuel value, coupled with the Pitchfork\\\'s high durability and speed, makes Turfs one of the easiest options for fueling Campfires and Fire Pits. Turfs are not renewable, however.\\r\\n\\r\\nDug up Turf can be replaced with other kinds of Turfs (e.g. Wooden Flooring). This is useful for decoration or for preventing Lureplants and Eyeplants from spawning.', 'Pitchfork.png', 'Tools', 'Science Machine', 'Twigs', 2, 'Flint', 2, '', 0, '17', '200 uses', 11, 'Craft a prototype in science machine'),
('Razor', 'The Razor is a craftable Tool Item found in the Tools Tab. It requires 2 Twigs and 2 Flints to craft, and a Science Machine to prototype. Unlike other Tools, on pc it cannot be equipped, and to be used it has to be lifted and used on a target instead. Players using a Controller have to simply be near an entity that can be shaved for the \\\"Shave\\\" prompt to appear. Since it has no durability, the Razor has infinite uses.', 'Razor.png', 'Tools', 'Science Machine', 'Twigs', 2, 'Flint', 2, '', 0, '', 'Infinite', 12, ''),
('Feather Pencil', 'The Feather Pencil is a craftable Item located in the Tools Tab. It requires a Science Machine to prototype and 1 Twigs, 1 Charcoal and 1 Jet Feather to craft. The Feather Pencil can be used to draw an Item on a Mini Sign. The closest Item placed on the ground is what will be drawn on the Mini Sign when using a Feather Pencil.<br>Don\'t Starve Together, the Feather Pencil can additionally be used to craft a Map Scroll.', 'Feather_Pencil.png', 'Tools', 'No Science requirement', 'Charcoal', 1, 'Jet Feather', 1, 'Twigs', 1, '', '', 13, 'It requires a Science Machine to prototype and 1 Twigs, 1 Charcoal and 1 Jet Feather to craft. '),
('Pocket Scale', 'The Pocket Scale is a craftable Item exclusive to Don\\\'t Starve Together, introduced in Return of Them.<br>\\r\\nThe Pocket Scale is used to measure Fishes Weights. It can be used to anticipate the results of the Fish Scale-O-Matic or if Crabby Hermit will accept it.', 'Pocket_Scale.png', 'Tools', 'Science Machine', 'Log', 1, 'Cut Stone', 1, 'Gold Nugget', 1, '', '100 uses', 14, ''),
('Luxury Axe', 'The Luxury Axe is a version of the normal Axe that has four times as much durability and requires Gold Nuggets instead of Flint, making it easily renewable. It requires 4 Twigs and 2 Gold Nuggets to craft, and an Alchemy Engine to prototype. It has 400 uses, 4 times as many as the regular Axe. When used as a weapon it deals the same amount of damage as a regular Axe. It also has the same efficiency as the regular Axe, requiring 5, 10, and 15 chops to fell trees depending on their size.\\r\\n\\r\\n', 'Luxury_Axe.png', 'Tools', 'Alchemy Engine', 'Twigs', 4, 'Gold Nugget', 2, '', 0, '27.2', '400 uses', 15, 'It requires 4 Twigs and 2 Gold Nuggets to craft, and an Alchemy Engine to prototype.'),
('Regal Shovel', 'The Regal Shovel is a variant of the normal Shovel that has four times as much durability and requires Gold instead of Flint. It requires 2 Gold Nuggets and 4 Twigs to craft and an Alchemy Engine to prototype. Regal Shovel has 100 uses, 4 times as many as regular shovel. It deals the same 17 damage on each strike as the normal Shovel.', 'Regal_Shovel.png', 'Tools', 'Alchemy Engine', 'Twigs', 4, 'Gold Nugget', 2, '', 0, '17', '100 uses', 16, 'It requires 2 Gold Nuggets and 4 Twigs to craft and an Alchemy Engine to prototype.'),
('Opulent Pickaxe', 'The Opulent Pickaxe is a variant of the normal Pickaxe that has four times as much durability and requires Gold instead of Flint, allowing Flint to be saved for other uses. It requires 2 Gold Nuggets and 4 Twigs to craft and an Alchemy Engine to prototype. Opulent Pickaxe has 132 uses, 4 times as many as the normal Pickaxe. It has the same mining efficiency (6 hits per boulder) and damage (27.2 damage per strike) as the normal Pickaxe.', 'Opulent_Pickaxe.png', 'Tools', 'Alchemy Engine', 'Twigs', 4, 'Gold Nugget', 2, '', 0, '27.2', '132 uses', 17, 'It requires 2 Gold Nuggets and 4 Twigs to craft and an Alchemy Engine to prototype.'),
('Saddle', 'To mount a Beefalo, the Beefalo in question must first be tamed by feeding it Cut Grass, Cut Reeds, Twigs, or any Vegetable and Fruit. Afterwards the Saddle may be placed on the Beefalo to allow mounting. If a player attempts to saddle a Beefalo with obedience lower than 10%, it will reject the saddle and attack the player.<br>\\r\\nAfter some time being mounted, the Beefalo will eject the mounted player. No damage is inflicted to the player upon being dismounted, and the Beefalo can be mounted again immediately afterwards.', 'Saddle.png', 'Tools', 'Alchemy Engine', 'Beefalo_Wool', 4, 'Pig_Skin', 4, 'Gold Nugget', 4, '', '5 uses', 18, 'The Saddle is a Tool item that can be used to mount Beefalo. It is crafted at the Alchemy Engine with 4 Pig Skins, 4 Gold Nuggets and 4 Beefalo Wool.'),
('Campfire', 'A Campfire is a key to basic survival in the world. It provides Light, Heat and allows Food to be cooked.<br>It requires 3 Cut Grass and 2 Logs to create and is available from the beginning of the game. It is cheaper than a Fire Pit in terms of resources, but also less efficient, as it can not be re-lit. The fuel will burn twice as fast, it is more susceptible to Rain, and in a sense, it is less safe, as it may set nearby flammable objects on fire. When burnt out, the Campfire drops 1 Ash.', 'Campfire_Build.png', 'Light', 'No Science requirement', 'Log', 2, 'Cut_Grass', 3, '', 0, '', '', 21, 'It requires 3 Cut Grass and 2 Logs to create and is available from the beginning of the game.'),
('Firepit', 'A Fire Pit is the center of most base camps. It provides light and heat, allows food to be cooked, and is a contained, \\\'safer\\\' fire than a Campfire (it will not set surrounding objects on fire).<br>It requires 2 Logs and 12 Rocks to craft and, like the Campfire, is available from the beginning of the game. It is a persistent structure, unlike Campfires, and can be re-lit by putting fuel in it. A Fire Pit is also more efficient than a Campfire, as the fuel will last 2 times longer, and it is less susceptible to Rain. It drops no Ashes when it burns out, but destroying it will', 'Firepit_Build.png', 'Light', 'No Science requirement', 'Log', 2, 'Rocks', 0, '', 0, '', '', 23, 'It requires 2 Logs and 12 Rocks to craft and, like the Campfire, is available from the beginning of the game. '),
('Torch', 'Torches burn (and as a result loses durability) while equipped, providing a source of light for the player. A Torch will last for 75 seconds (2.5 in-game clock segments). In Rain, a Torch may burn up to 150% faster depending on precipitation rate.', 'Torch.png', 'Light', 'No Science requirement', 'Cut_Grass', 2, 'Twigs', 2, '', 0, '17', '75 uses', 24, 'A Torch is a portable Light Item in Don\\\'t Starve. It can be crafted with 2 Cut Grass and 2 Twigs, and is available from the start of the game.'),
('Trap', 'A Trap is a Survival item used to catch small animals such as Rabbits, Frogs, and Spiders. It can be crafted at the beginning of the game with 6 Cut Grass and 2 Twigs.<br>Once set, Traps can be baited with food items attractive to said animals. Baited or not, a Trap will trigger once a small mob moves close enough to it.', 'Trap.png', 'Survival', 'No Science requirement', 'Cut_Grass', 6, 'Twigs', 2, '', 0, '', '8 uses', 25, 'It can be crafted at the beginning of the game with 6 Cut Grass and 2 Twigs.'),
('Pretty Parasol', 'The Pretty Parasol is a Survival item. Like a Umbrella, it negates Sanity loss caused by the Rain when equipped. If playing as WX-78, the Pretty Parasol will prevent damage caused by Rain and prevent being struck by Lightning.<br>\\r\\nIt requires 4 Twigs, 3 Cut Grass, and 6 Petals to craft and is available from the beginning of the game. It can also be used as a Fuel, providing the same burn time as a Log.<br>Like the Garland, the Pretty Parasol does not have durability but instead spoils over time.', 'Pretty_Parasol.png', 'Survival', 'No Science requirement', 'Twigs', 4, 'Cut_Grass', 3, 'Petals', 6, '', '', 26, 'It requires 4 Twigs, 3 Cut Grass, and 6 Petals to craft and is available from the beginning of the game. It can also be used as a Fuel, providing the same burn time as a Log.'),
('Telltale Heart', 'The Telltale Heart is a craftable Survival item only available in Don\\\'t Starve Together. It can be used to revive dead players by left-clicking on the ghost of the dead player. It can be crafted without a Science Machine using 3 Cut Grass and 1 Spider Gland.<br>Upon crafting the Telltale Heart, the player who crafted it will lose 40 Health. If a player does not have enough health they will not be able to craft it (if they lose the health while crafting, crafting will reduce them to 1 health, after which they will most likely die to the other damage source, such as freezing or fire).<br>After a living player gives the heart to a ghost, the living player receives 80 Sanity, and the ghost is revived with an additional 25% (1/4) of their maximum health removed along with normal resurrection penalties. The health penalty received by a Ghost using this item can be removed through the use of a Booster Shot. Ghost Players cannot haunt the heart to revive, they must have it given to them by a living character.<br>Players who have recently revived someone will be identified by a different examination quote.', 'Telltale_Heart.png', 'Survival', 'No Science requirement', 'Cut_Grass', 3, 'Spider_Gland', 1, '', 0, '-40 Health decrease', '1 use', 27, 'It can be used to revive dead players by left-clicking on the ghost of the dead player. It can be crafted without a Science Machine using 3 Cut Grass and 1 Spider Gland.'),
('Bird Trap', 'A Bird Trap is a Survival Item used to catch Birds. It is crafted using 3 Twigs and 4 Silk and requires a Science Machine to prototype. Bird Traps can be baited with Seeds to significantly increase the chance of catching a Bird, though it is not a requirement. Using a Feather Hat will increase the number of birds landing to speed up the process.<br>It appears that there is a chance a trap will fail to catch a Bird and simply break, leaving the Bird that triggered the Trap lying on the ground for a brief time before flying away. The failed Trap can still be picked up and reset, but this still costs one durability use. It is currently unknown whether the chance of a Trap failing is based on a certain probability, bird type, or player proximity.', 'Bird_Trap.png', 'Survival', 'Science Machine', 'Twigs', 3, 'Silk', 4, '', 0, '', '8 uses', 28, 'It is crafted using 3 Twigs and 4 Silk and requires a Science Machine to prototype.'),
('Backpack', 'The Backpack is a Survival Item that serves to expand the character\\\'s inventory. It requires 4 Cut Grass and 4 Twigs to craft and a Science Machine to prototype. The Backpack itself cannot be placed in the inventory or in Chests and only one may be equipped at a time.<br>When a Backpack is created it automatically equips itself in the Chest Slot if it is available. Wearing the Backpack provides 8 additional inventory slots. This item uses the same equipment slot as Armor and Vests, which means wearing one requires sacrificing the benefits of the other. Unlike other items that go into the Chest slot, Backpacks do not have durability.<br>Although Backpacks cannot be placed in the inventory or in Chests, they can be dropped on the ground and used for storage. Any item hovered over a Backpack while it\\\'s on the ground will give the \\\'Store\\\' option, allowing the pack to be filled without equipping it.', 'Backpack.png', 'Survival', 'Science Machine', 'Cut_Grass', 4, 'Twigs', 4, '', 0, '', '', 29, 'It requires 4 Cut Grass and 4 Twigs to craft and a Science Machine to prototype.'),
('Crock Pot', 'The Crock Pot is a Structure that is used to cook a variety of belly-filling dishes from basic Foods. It\\\'s found on the Food Tab, it requires a Science Machine to prototype, and it costs 3 Cut Stone, 6 Charcoal, and 6 Twigs to build.<br>Building a Crock Pot early on greatly enhances food\\\'s value and efficiency, and it can even make use of otherwise inedible items like Twigs and Monster Meat.', 'Crock_Pot_Build.png', 'Food', 'Science Machine', 'Cut Stone', 3, 'Charcoal', 6, 'Twigs', 6, '', '', 30, 'It requires a Science Machine to prototype, and it costs 3 Cut Stone, 6 Charcoal, and 6 Twigs to build.'),
('Basic Farm', 'Seeds planted in a Farm will grow a Fruit or Vegetable at random. Possible crops include Carrots, Corn, Eggplants, Pumpkins, Dragon Fruits, Durians and Pomegranates. Specific crops can be grown by using Crop Seeds. The speed at which the crops grow depends on the world temperature, availability of light, and Rain. Farms deplete after a number of harvests, and they need to be fertilized to grow more crops. Growing crops can be fertilized to speed up their growth. This fertilization only affects the crops, and will not affect the fertilization status of the Farm itself. During Winter, the crops will not grow, however, during the first and last few days of Winter, the temperature is warm enough to allow fertilizing the crops to work, even though they won\\\'t grow on their own. When the world temperature is over 28 degrees, the crops grow twice as fast. Crops only grow in the presence of light; at nightfall, they stop growing until the following sunrise, unless they are near a light source. If a crop has finished growing, it will not spoil in the Farm if not harvested. Like any other structure, Farms can be destroyed using a Hammer or a Deconstruction Staff.', 'Basic_Farm.png', 'Food', 'Science Machine', 'Cut_Grass', 8, 'Manure', 4, 'Log', 4, '', '', 31, 'The Basic Farm can be prototyped at a Science Machine and requires 8 Grass, 4 Manure, and 4 Logs to build. The Basic Farm yields 20 harvests before requiring fertilization. Crops take about 20 daylight minutes to finish growing. To avoid waiting, 4 Manure, 16 Rot/Rotten Eggs, or 3 Guano can be used to fully grow a crop planted in the Basic Farm.'),
('Improved Farm', 'The Improved Farm is an enhanced version of the Basic Farm. It can be prototyped at an Alchemy Engine and requires 10 Grass, 6 Manure, and 4 Rocks to build. The Improved Farm yields 30 harvests before requiring fertilization. Crops take about 10 daylight minutes to grow. To avoid waiting, 2 Manure, 8 Rot/Rotten Eggs, or 2 Guano can be used to fully grow a crop planted in the Improved Farm.', 'Improved_Farm.png', 'Food', 'Alchemy Engine', 'Cut_Grass', 10, 'Manure', 6, 'Rocks', 4, '', '', 32, 'It can be prototyped at an Alchemy Engine and requires 10 Grass, 6 Manure, and 4 Rocks to build.'),
('Bee Box', 'A Bee Box is a craftable Structure that uses Bees to accumulate Honey that can be harvested. Bee Boxes are found in the Food Tab and require a Science Machine to prototype. It takes 1 Honeycomb, 4 Bees, and 2 Boards to build. When destroyed by a Hammer, it will return 1 Honeycomb and 1 Boards, and will release any Bees inside the Box.', 'Bee_Box_Build.png', 'Food', 'Science Machine', 'Boards', 2, 'Honeycomb', 1, 'Bee', 4, '', '', 33, 'It takes 1 Honeycomb, 4 Bees, and 2 Boards to build. When destroyed by a Hammer, it will return 1 Honeycomb and 1 Boards, and will release any Bees inside the Box.'),
('Science Machine', 'The Science Machine is the tier 1 Science station. It costs 1 Gold Nugget, 4 Logs, and 4 Rocks to craft, and it is available from the start of the game. Like other crafting stations, standing near the Science Machine allows prototyping new recipes. Prototyping items for the first time will grant the player 15 Sanity. Once prototyped, items can be crafted without being near a Science Machine.', 'Science_Machine.png', 'Science', 'No Science requirement', 'Gold Nugget', 1, 'Log', 4, 'Rocks', 4, '', '', 34, 'It costs 1 Gold Nugget, 4 Logs, and 4 Rocks to craft, and it is available from the start of the game. Like other crafting stations, standing near the Science Machine allows prototyping new recipes.'),
('Alchemy Engine', 'The Alchemy Engine is the tier 2 Science station. It requires a Science Machine to prototype for all characters except Wickerbottom, and costs 4 Boards, 2 Cut Stones, and 6 Gold Nuggets to craft. Prototyping an Item using the Alchemy Engine will increase Sanity by 15.', 'Alchemy_Engine_Build.png', 'Science', 'Science Machine', 'Boards', 4, 'Cut Stone', 2, 'Gold Nugget', 6, '', '', 35, 'It requires a Science Machine to prototype for all characters except Wickerbottom, and costs 4 Boards, 2 Cut Stones, and 6 Gold Nuggets to craft.'),
('Grass Suit', 'The Grass Suit is the weakest wearable Armor, crafted in the Fight tab. It requires 10 Cut Grass and 2 Twigs to craft and is available from the beginning of the game.<br>It has 225 durability and absorbs 60% of physical damage. It can also be added to a Campfire or Fire Pit for fuel, even when its durability is nearly gone. Not considering the armor\\\'s durability, the grass suit effectively adds 225 Health Meter.png to the average survivor.', 'Grass_Suit.png', 'Fight', 'No Science requirement', 'Cut_Grass', 10, 'Twigs', 2, '', 0, '', '158 hp', 36, 'It requires 10 Cut Grass and 2 Twigs to craft and is available from the beginning of the game.'),
('Spear', 'The Spear is a Melee Weapon crafted from the Fight Tab. It requires 1 Flint, 1 Rope, and 2 Twigs to craft and a Science Machine to prototype. It can also be found near the walled area where the Box Thing lies.<br>The Spear deals 34 damage per hit, making it the second weakest melee weapon in the game. Its Durability allows for 150 hits, meaning each hit will reduce it by 0.66%.', 'Spear.png', 'Fight', 'Science Machine', 'Twigs', 2, 'Rope', 1, 'Flint', 1, '34', '150 uses', 37, 'The Spear is a Melee Weapon crafted from the Fight Tab. It requires 1 Flint, 1 Rope, and 2 Twigs to craft and a Science Machine to prototype. It can also be found near the walled area where the Box Thing lies.'),
('Log Suit', 'Protects you from some damage.<br>The Log Suit is a wearable Armor, crafted in the Fight Tab. It requires 8 Logs and 2 Ropes to craft and a Science Machine to prototype.<br>It has 450 durability and absorbs 80% of physical damage. It can also be added to a Campfire or Fire Pit for fuel, even when its durability is nearly gone. Not considering its durability, the log suit effectively adds 600 hp to a survivor with 150 HP.', 'Log_Suit.png', 'Fight', 'Science Machine', 'Log', 8, 'Rope', 2, '', 0, '', '315 hp', 38, 'The Log Suit is a wearable Armor, crafted in the Fight Tab. It requires 8 Logs and 2 Ropes to craft and a Science Machine to prototype.'),
('Ham Bat', 'The Ham Bat is a Melee Weapon which deals 59.5 damage. It spoils after 10 days and has unlimited uses during this period. Despite being made out of meat, it cannot be eaten by the player or other mobs and will not anger a Bunnyman when in the player\\\'s possession.<br>The Ham Bat requires 1 Pig Skin, 2 Twigs, and 2 Meat to craft and an Alchemy Engine to prototype.', 'Ham_Bat.png', 'Fight', 'Alchemy Engine', 'Pig_Skin', 1, 'Twigs', 2, 'Meat', 2, '59.5', '10 days', 39, 'The Ham Bat requires 1 Pig Skin, 2 Twigs, and 2 Meat to craft and an Alchemy Engine to prototype.'),
('Endothermic Fire', 'The Endothermic Fire is a craftable Light Tab Structure introduced in the Reign of Giants DLC. It requires a Science Machine to prototype and costs 2 Nitre and 3 Cut Grass to craft.<br>An Endothermic Fire provides light and cools the player. It can be fueled with the same items as a regular fire (see Fuel), in addition to Nitre. An Endothermic Fire is unable to cook food. When burnt out, it drops Ashes.', 'Endothermic_Fire_Build.png', 'Light', 'Science Machine', 'Nitre', 2, 'Cut_Grass', 3, '', 0, '', '', 40, 'It requires a Science Machine to prototype and costs 2 Nitre and 3 Cut Grass to craft.'),
('Endothermic Fire Pit', 'The Endothermic Fire Pit is the permanent version of the Endothermic Fire. It requires an Alchemy Engine to prototype and costs 2 Nitre, 4 Cut Stone, and 2 Electrical Doodads to craft.<br>Endothermic Fire Pit is more fuel-efficient than the Endothermic Fire. Each fuel item burns as long as they would in a Fire Pit, which is twice as long as the burn time in a Campfire or Endothermic Fire.', 'Endothermic_Fire_Pit_Build.png', 'Light', 'Alchemy Engine', 'Nitre', 2, 'Cut Stone', 4, 'Electrical_Doodad', 2, '', '', 41, 'It requires an Alchemy Engine to prototype and costs 2 Nitre, 4 Cut Stone, and 2 Electrical Doodads to craft.'),
('Dark Sword', 'The Dark Sword is a Magical Melee Weapon. It requires a Shadow Manipulator to prototype and costs 5 Nightmare Fuel and 1 Living Log to craft. The Dark Sword does 68 damage per hit and has 100 uses. It also drains Sanity by 20 Sanity Meter.png/minute while equipped. It is one of Maxwell\\\'s starting items in the singleplayer game.<br>The Dark Sword is the strongest melee weapon in the game in terms of reliable, player-dealt damage. It can be used against any Mob in the game, not just against Shadow Creatures. Due to their perks, the Dark Sword proves the most useful when wielded by Wolfgang, Maxwell, and Wigfrid.', 'Dark_Sword.png', 'Magic', 'Shadow Manipulator', 'Nightmare_Fuel', 5, 'Living_Log', 1, '', 0, '68', '100 uses', 42, 'It requires a Shadow Manipulator to prototype and costs 5 Nightmare Fuel and 1 Living Log to craft.'),
('Shadow Manipulator', 'The Shadow Manipulator is the tier 2 Magic station which unlocks all of the Magic Tab recipes. It requires a Prestihatitator to prototype and costs 3 Living Logs, 1 Purple Gem, and 7 Nightmare Fuel to craft. Prototyping an item using the Shadow Manipulator will increase Sanity by 15, like any other station.', 'Shadow_Manipulator_64.png', 'Magic', 'Prestihatitator', 'Living_Log', 3, 'Purple_Gem', 1, 'Nightmare_Fuel', 7, '', '', 43, 'It requires a Prestihatitator to prototype and costs 3 Living Logs, 1 Purple Gem, and 7 Nightmare Fuel to craft. Prototyping an item using the Shadow Manipulator will increase Sanity by 15, like any other station.');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `craft`
--
ALTER TABLE `craft`
  ADD PRIMARY KEY (`item_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `craft`
--
ALTER TABLE `craft`
  MODIFY `item_id` int(50) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=44;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
